### ISSUE TITLE
Node run failed

### ISSUE THREAD

**Issue by tenhobi** [actions/upload-release-asset#14]
Hi,

I am trying to upload a pdf to release created in the previous step in build and for some reason, the action fails.

Set up URL is a valid path.

What can I do to fix this issue?

https://github.com/tenhobi/bach_test/commit/0c039950693c88a2fc4e55c605376c4347ca7dcb/checks?check_suite_id=316933806

```
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: 'https://github.com/tenhobi/bach_test/releases/tag/${{ steps.semver-release.outputs.tag }}'
          asset_path: ./BP_Jan_Bittner.pdf
          asset_name: BP_Jan_Bittner.pdf
          asset_content_type: application/pdf
```

![image](https://user-images.githubusercontent.com/5287596/69091347-67969180-0a4a-11ea-8085-ef0fa56535e7.png)

whole settings

```
name: release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Rename PDF
        run: mv main.pdf BP_Jan_Bittner.pdf

      - name: Semver Release
        id: semver-release
        uses: K-Phoen/semver-release-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_branch: master

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: 'https://github.com/tenhobi/bach_test/releases/tag/${{ steps.semver-release.outputs.tag }}'
          asset_path: ./BP_Jan_Bittner.pdf
          asset_name: BP_Jan_Bittner.pdf
          asset_content_type: application/pdf

```
