### ISSUE TITLE
Support matrix build

### ISSUE THREAD

**Issue by imbsky** [actions/upload-release-asset#16]

**Comment by IAmHughes** [comment]
@imbsky did you mean to open this? I’ll close it but happy to re-open if you edit your original comment body 👍

**Comment by imbsky** [comment]
Oh, when I hit return, it seemed to be opened...

**Comment by imbsky** [comment]
@IAmHughes Currently a validation error occurs when uploading assets from multiple OSs to release in a matrix build. It should be fixed.

**Comment by imbsky** [comment]
In other words, we can't upload software-name-here-x86_64-macOS-latest.tar.gz and software-name-here-x86_64-ubuntu-latest.tar.gz to latest release.

**Comment by imbsky** [comment]
and I can't re-open this issue, there is no button to re-open.

**Comment by IAmHughes** [comment]
I reopened it for you @imbsky, because the original issue was blank I wasn’t sure. Thanks!

**Comment by imbsky** [comment]
Thanks for quick response!

**Comment by arlyon** [comment]
Running into this. Trying to have a build with the following job structure:

```
build(mac)       build(linux)        build(win)
    │                  │                 │
    └──────────────────┼─────────────────┘
                       │
                create_release()
                       │
    ┌──────────────────┼─────────────────┐
    │                  │                 │
upload(mac)       upload(linux)      upload(win)
```

This is split into 3 jobs, 2 of which use matrices. It is not possible
to run `create-release` (https://github.com/actions/create-release).
Because it is impossible to get outputs from previous jobs (even
ones that it ["needs"](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idneeds)),
and because create-release cannot be run per-matrix this setup
is impossible.

**Comment by imbsky** [comment]
This supports matrix build. I don't know because I haven't read the code at all, but can't we support it with the same approach?
https://github.com/softprops/action-gh-release

**Comment by justin1121** [comment]
Hey @arlyon that looks like a good solution but one thing I can't figure out is how to get the upload_url from the create_release job to the upload jobs. Thanks!

**Comment by Viladoman** [comment]
Same issue here. Trying to upload to a release 3 assets for 3 different platforms and failing on 'create_release' when the job for the second platform is running. 
```
Run actions/create-release@v1
##[error]Validation Failed
```
Any ideas?

**Comment by Margen67** [comment]
I got around this by having a seperate job do release creation. Files needed for release can be uploaded/downloaded via artifacts.

**Comment by vovawed** [comment]
I have the same problem, I've tried `${{ needs.create-release.outputs.upload_url }}` but it doesn't work

**Comment by kmturley** [comment]
I have a workaround for this which creates the release first, before going into matrix mode:

```
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build_release:
    name: Build release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            zip_name: plugin-linux
            generator: Unix Makefiles
          - os: macos-latest
            zip_name: plugin-mac
            generator: Xcode
          - os: windows-latest
            zip_name: plugin-win
            generator: Visual Studio 16 2019
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install cmake gcc

      - name: Install macOS dependencies
        if: matrix.os == 'macOS-latest'
        run: brew install cmake

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install zip

      - name: Build
        shell: bash
        run: cmake --build ./build --config Release

      - name: Compress
        shell: bash
        run: |
          cd ./build/VST3/Release
          zip -r ../${{ matrix.zip_name }}.zip *

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/VST3/${{ matrix.zip_name }}.zip
          asset_name: ${{ matrix.zip_name }}.zip
          asset_content_type: application/zip
```

Full source code is here:
https://github.com/studiorack/studiorack-plugin/blob/master/.github/workflows/release.yml
