### ISSUE TITLE
How to upload multiple assets?

### ISSUE THREAD

**Issue by riobard** [actions/upload-release-asset#28]
I have several build artifacts to upload together. What is the correct way to do so?

**Comment by tamalsaha** [comment]
https://github.com/softprops/action-gh-release

**Comment by haampie** [comment]
For everybody struggling with this, just add **multiple** steps:

```
- name: Upload binaries
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    ...
- name: Upload docs
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    ...
- name: Upload sources
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    ...
```
