### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Arjan-Zuidema** [actions/upload-release-asset#35]
I have a workflow that build two versions of an application. One for Windows and one for MacOS. These builds run in parallel. When finished a new job is spawned to create a GitHub release ad publish the files to that release.

I am using `actions/download-artifact@v1` to download the artifacts from the previous jobs. When trying to upload the files to the release I get an error: `EISDIR: illegal operation on a directory, read`. See log of the `actions/upload-release-asset` step below:

```
Run actions/upload-release-asset@v1
  with:
    upload_url: https://uploads.github.com/repos/MyAlbum/Sketch2Blueprint/releases/24428353/assets{?name,label}
    asset_path: /home/runner/work/_temp/latest-mac.yml
    asset_name: latest-mac.yml
    asset_content_type: text/yaml
  env:
    GITHUB_TOKEN: ***
##[error]EISDIR: illegal operation on a directory, read
```

**Comment by Margen67** [comment]
@Arjan-Zuidema Are you sure it's not a directory?

**Comment by Arjan-Zuidema** [comment]
The files are downloaded using `actions/download-artifact@v1` with the exact same paths, so how can it be a directory? Maybe it's a bug in `actions/download-artifact@v1` but I don't know.

**Comment by the-mikedavis** [comment]
@Arjan-Zuidema I just ran into this as well. You probably want to `download-artifact` into your current directory. `download-artifact` will unzip your artifact into a directory given as the `path` argument

```yml
    - name: Upload the artifact
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: path/to/my/artifact.tar.gz

# ... next job or whenever you need the artifact

    - name: Download the artifact
      uses: actions/download-artifact@v1
      with:
        name: my-artifact
        path: ./

    - name: Upload the release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifact.tar.gz
        asset_name: artifact.tar.gz
        asset_content_type: application/gzip
```
