### ISSUE TITLE
Dynamic Filenames (or an array?)

### ISSUE THREAD

**Issue by eduncan911** [actions/upload-release-asset#4]
Hello!

So our build job generates around 12 or so asset files with various extensions, signatures, sha, etc.

The thing is, we have dynamic names in our filenames based on dates.  Would something like this work?

    - name: Upload Asset to Release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_FOR_RELEASES }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/usbarmory-mark-one-debian_stretch-base_image-usd-$(shell /bin/date -u "+%Y%m%d").zip
        asset_name: usbarmory-mark-one-debian_stretch-base_image-usd-$(shell /bin/date -u "+%Y%m%d").zip
        asset_content_type: application/zip

I'm asking because I'm still setting things up and it's going to be a while. Figured I'd ask before planning all around this.

---

As an alternative, could we add a way to pass/read in an array?  Or, to run a bash command to obtain the filenames?

Because I can easily do something like this:

    ls -1 release/

Where it would list all the files we want to upload.  

Thoughts?

**Comment by IAmHughes** [comment]
Hey @eduncan911 

How does this example look as a way to pass in variable inputs:

```

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Set an output
      id: get-date
      run: |
        echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
    - name: Use the output
      run: |
        echo 'The output date is ${{ steps.get-date.outputs.date }}'
```
