### ISSUE TITLE
Parentheses in asset_name get replaced with periods

### ISSUE THREAD

**Issue by archon810** [actions/upload-release-asset#57]
Hi,

We have the following action:

```
# Upload Development APK to Release
      - name: Upload Development APK to Release
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "app/apks/${{ steps.generate_apk_names.outputs.NAME_DEVELOPMENT }}"
          asset_name: ${{ steps.generate_apk_names.outputs.NAME_DEVELOPMENT }}
          asset_content_type: application/zip
```

Our `NAME_DEVELOPMENT` contains parentheses (for example, `app.prod-v1.3.0-(15-5)-6064eac-release.apk`), but upon upload, the files end up with `(` and `)` replaced with periods, like so: `app.prod-v1.3.0-.15-5.-6064eac-release.apk`.

NAME_DEVELOPMENT is used by another action (`actions/upload-artifact`) and the same name gets uploaded properly there, with parentheses not replaced.

Is this a bug in this action?

Thanks.
