### ISSUE TITLE
Add the ability to use wildcards for uploading files.

### ISSUE THREAD

**Issue by opussf** [actions/upload-release-asset#60]
Allow multiple files to be uploaded, either from a list, or from wildcard expansion.

Many build systems create artifact files that do not have a name known before hand, and may want to publish multiple files.
For example, a zip filename that includes the tag, or the branch that it was created from, or even for what environment it is built for (Windows / MacOS / iOS / Android / etc.)   And adding supporting files, such as an MD5 / SHA1 file, or a signature file.

This would probably require removing the 'asset_name' and 'asset_content_type' attributes to have these generated by this action.

IE:  
asset_path: |
    path/to/files/*.zip 
    path/to/files/special_file_name

**Comment by eine** [comment]
Dup of #47. Ref #58.

**Comment by alexellis** [comment]
I would also be supportive of this

@opussf if it's of use to you, feel free to use: https://github.com/marketplace/actions/upload-release-assets

**Comment by Felixoid** [comment]
Hey @alexellis, looks good. Do you consider to add a way to define the tag for upload manually? Or using `${{ github.event.release }}` object for it?

**Comment by alexellis** [comment]
I would accept a PR for that 👍

**Comment by eyal0** [comment]
@opussf You can accomplish this by setting an environment variable and then using it?

```
      - run: echo "FOO=$(echo hello)" >> $GITHUB_ENV
      - name: Upload windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pcb2gcode-windows/pcb2gcode-${{ env.FOO }}.tar
```

But still, having wildcard support would be nice.  It's not clear to me how you would specify multiple asset_names for multiple asset_paths.

**Comment by maelvls** [comment]
As a workaround, I have been using @alexellis's [alexellis/upload-assets](https://github.com/marketplace/actions/upload-release-assets). For example ([source](https://github.com/maelvls/ocamlyices2/blob/554893d467a4bf3e9b0b630833b417348b15e771/.github/workflows/ci.yml#L123-L127)):

```yaml
  release:
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: actions/download-artifact@v2
        with:
          name: gmp

      - uses: alexellis/upload-assets@0.2.2          # ✨✨✨
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./gmp/*"]'
```
