### ISSUE TITLE
Still getting EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by nuhkoca** [actions/upload-release-asset#67]
Hello,

I am still getting `EISDIR: illegal operation on a directory, read` error despite the fact that I followed solutions in #35. Here is my sample `.yml` content. Can you please tell me what I am doing wrong? Thanks!

```
      - name: Upload Sample Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: release-apk
          path: app_name/build/outputs/apk

      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: release-apk
          path: release-apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release-apk
          asset_name: ${{ github.ref }}
          asset_content_type: application/zip
```
